version: 2
jobs:
  test:
    docker:
      - image: node:10.16.3-buster
    steps:
      - checkout
      - run:
          name: Running tests
          command: |
            npm install
            npm test
      - run:
          name: Running coverage
          command: bash <(curl -s https://codecov.io/bash)      
  deployment:
    docker:
      - image: node:10.16.3-buster
    steps:
      - checkout
      - run:
          name: Deploying
          command: |
            npm install
            npm run deploy          
workflows:
  version: 2
  build:
    jobs:
      - test
      - deployment:
          requires:
            - test
          filters:
            branches:
              only:
                - master
